version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./data:/data
      - ./mariadb_data:/var/lib/mysql
      - ./sql_import:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
      